[tool.poetry]
name = "qmk_firmware"
version = "0.13.5"
description = "Quantum Mechanical Keyboard Firmware"
authors = ["Jack Humbert <jack.humb@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
qmk = "^0.1.0"
appdirs = "^1.4.4"
argcomplete = "^1.12.3"
colorama = "^0.4.4"
hid = "^1.0.4"
hjson = "^3.0.2"
jsonschema = ">=3"
milc = ">=1.4.2"
Pygments = "^2.9.0"
pyusb = "^1.2.0"
qmk-dotty-dict = "^1.3.0"

[tool.poetry.dev-dependencies]
nose2 = "^0.10.0"
flake8 = "^3.9.2"
pep8-naming = "^0.12.1"
yapf = "^0.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
