[tool.poetry]
name = "qmk_firmware"
version = "0.9.58"
description = ""
authors = ["Takahiro Yoshihara <tacahiroy@gmail.com>"]
license = "GPL-2.0-only"

[tool.poetry.dependencies]
python = "^3.8"
appdirs = "*"
argcomplete = "*"
colorama = "*"
hjson = "*"
pygments = "*"
milc = "*"
dotty-dict = "^1.3.0"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
nose2 = "*"
flake8 = "*"
pep8-naming = "*"
yapf = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
